# https://dev.azure.com/home-assistant

trigger:
  tags:
    include:
    - '*'
pr: none
variables:
  - name: versionWheels
    value: '1.14.2-3.8-alpine3.12'
resources:
  repositories:
    - repository: azure
      type: github
      name: 'home-assistant/ci-azure'
      endpoint: 'home-assistant'

jobs:
- template: templates/azp-job-wheels.yaml@azure
  parameters:
    builderVersion: '$(versionWheels)'
    builderApk: 'build-base;gfortran;openblas-dev;lapack-dev;openblas-dev'
    builderPip: 'Cython;numpy'
    builderPath: 'scipy'
    wheelsLocal: true
    auditwheel: true
    preBuild:
    - script: |
        set -xe

        version="$(head -n 1 requirements.txt | cut -d '=' -f 3)"
        git clone --depth 1 -b "v${version}" https://github.com/scipy/scipy

        cd scipy
        git apply ../missing-int64_t.patch
        rm -rf .git
      displayName: 'Setup scipy'
